# Generated by Django 3.2.24 on 2024-02-18 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent edit'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(blank=True, help_text='List of ingredients', max_length=500),
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
