# Generated by Django 3.2.24 on 2024-02-18 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240218_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='price',
        ),
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='platform_commission',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='selling_price',
            field=models.PositiveSmallIntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
