# Generated by Django 3.2.24 on 2024-02-18 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240218_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='measurement_unit',
            field=models.CharField(choices=[('gm', 'Grams'), ('kg', 'Kilograms'), ('mL', 'Milliliters'), ('L', 'Liters'), ('pc', 'Pieces')], default='gm', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for Approval'), ('approved', 'Approved'), ('discontinued', 'Discontinued')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
